# Post.create(title: "Test1", content: "This is a test")
# Post.create(title: "Test2", content: "This is a test")
# Post.create(title: "Test3", content: "This is a test")
# Post.create(title: "Test4", content: "This is a test")
# Post.create(title: "Test5", content: "This is a test")
# Post.create(title: "Test6", content: "This is a test")
